package service_test

const (
	ValidAdminToken  = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AYXp0bGFuLmluIiwiaGFuZGxlIjoiZGVtbyIsInV1aWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEifQ.dpM9Ij_Y25A5yNiVTt8hI-ZtjDqUfvbAFdtU9-RyDbs"
	ValidUserToken   = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdGFkbWluQGF6dGxhbi5pbiIsImhhbmRsZSI6Im5vdGFkbWluIiwidXVpZCI6IjIyMjIyMjIyLTIyMjItMjIyMi0yMjIyLTIyMjIyMjIyMjIyMiJ9.H_m-iWN4M1aZNZ3CB914kFm3JkQzJRy5x9uc6a0KE9c"
	ValidTokenNoUser = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vb25lQG5vb25lLm9uZSIsImhhbmRsZSI6Im5vcGUiLCJ1dWlkIjoiMTExMTExMTEtMjIyMi0zMzMzLTQ0NDQtMTExMTExMTExMTExIn0.yxhQWKYh6TW6DpfaYHM0LvDNKGSoy080jGvyMg23wYQ"
	InvalidToken     = "Bearer abcdefghijklmnopqrstuvwxyz"
)
