package service_test

const (
	ValidToken = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AYXp0bGFuLmluIiwiaGFuZGxlIjoiZGVtbyIsInV1aWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEifQ.z9ianXBWpC2rsRG0G1GHG16mYqYSSN3bfoQi5h5Hv_Y"
	ValidTokenNoUser = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByaXlhdmtrYW5lcmlhQGdtYWlsLmNvbSIsImhhbmRsZSI6InByaXlhdiIsInV1aWQiOiIzNjNjZjc5MS05N2MzLTRiODQtODYwZS00MjcwZTVjMzQ2MDkifQ.G72qPOvDhNJp9mkut_VtNBU1CNs3uL7zbyhXQZ74Xp4"
	InvalidTokenFormat = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlbW9AYXp0bGFuLmluIiwiaGFuZGxlIjoiZGVtbyIsInV1aWQiOiIxMTExMTExMS0xMTExLTExMTEtMTExMS0xMTExMTExMTExMTEifQ.z9ianXBWpC2rsRG0G1GHG16mYqYSSN3bfoQi5h5Hv_Y"
	InvalidToken = "Bearer abcdefghijklmnopqrstuvwxyz"
)