package apis

import (
	"github.com/PureML-Inc/PureML/server/apis/service"
	"github.com/PureML-Inc/PureML/server/config"
	"github.com/PureML-Inc/PureML/server/core"
	"github.com/PureML-Inc/PureML/server/docs" // docs is generated by Swag CLI
	"github.com/PureML-Inc/PureML/server/middlewares"
	_ "github.com/joho/godotenv/autoload"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// const trailedPath = "/_/"

func InitApi(app core.App) (*echo.Echo, error) {
	// Echo instance
	e := echo.New()

	// Middleware
	// e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.Use(middlewares.AuthenticateJWT(app))

	// bindStaticUI(e)

	rg := e.Group("/api")

	//Health API
	service.BindHealthApi(app, rg)

	//Swagger API
	rg.GET("/swagger/*", echoSwagger.WrapHandler)
	docs.SwaggerInfo.Title = "PureML API Documentation"
	docs.SwaggerInfo.Description = "API Documentation for PureML backend"
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = config.GetHost()
	docs.SwaggerInfo.BasePath = "/api/"
	docs.SwaggerInfo.Schemes = []string{config.GetScheme()}

	//Org APIs
	service.BindAdminApi(app, rg)
	service.BindOrgApi(app, rg)
	service.BindUserOrgApi(app, rg)
	service.BindUserApi(app, rg)

	//Model APIs
	service.BindModelApi(app, rg)
	service.BindModelReadmeApi(app, rg)
	service.BindModelBranchApi(app, rg)
	service.BindModelBranchVersionApi(app, rg)
	service.BindModelReviewApi(app, rg)
	service.BindModelLogsApi(app, rg)
	service.BindModelActivityApi(app, rg)

	//Dataset APIs
	service.BindDatasetApi(app, rg)
	service.BindDatasetReadmeApi(app, rg)
	service.BindDatasetBranchApi(app, rg)
	service.BindDatasetBranchVersionApi(app, rg)
	service.BindDatasetReviewApi(app, rg)
	service.BindDatasetLogsApi(app, rg)
	service.BindDatasetActivityApi(app, rg)

	//Secret APIs
	service.BindSecretsApi(app, rg)

	return e, nil
}

// StaticDirectoryHandler is similar to `echo.StaticDirectoryHandler`
// but without the directory redirect which conflicts with RemoveTrailingSlash middleware.
//
// If a file resource is missing and indexFallback is set, the request
// will be forwarded to the base index.html (useful also for SPA).
//
//	@see	https://github.com/labstack/echo/issues/2211
// func StaticDirectoryHandler(fileSystem fs.FS, e *echo.Echo, indexFallback bool) echo.HandlerFunc {
// 	return func(c echo.Context) error {
// 		p := c.Param("*")

// 		// escape url path
// 		tmpPath, err := url.PathUnescape(p)
// 		if err != nil {
// 			return fmt.Errorf("failed to unescape path variable: %w", err)
// 		}
// 		p = tmpPath

// 		// fs.FS.Open() already assumes that file names are relative to FS root path and considers name with prefix `/` as invalid
// 		name := filepath.ToSlash(filepath.Clean(strings.TrimPrefix(p, "/")))

// 		fileErr := e.FileFS(c.Path(), name, fileSystem)

// 		if fileErr != nil && indexFallback && errors.Is(fileErr, echo.ErrNotFound) {
// 			return e.FileFS("index.html", fileSystem)
// 		}

// 		return fileErr
// 	}
// }

// bindStaticUI registers the endpoints that serves the static  UI.
// func bindStaticUI(e *echo.Echo) error {
// 	// redirect to trailing slash to ensure that relative urls will still work properly
// 	e.GET(
// 		strings.TrimRight(trailedPath, "/"),
// 		func(c echo.Context) error {
// 			return c.Redirect(http.StatusTemporaryRedirect, trailedPath)
// 		},
// 	)

// 	// e.FileFS(trailedPath+"*", "index.html", ui.BuildIndexFS)
// 	// serves static files from the /ui/public/build directory
// 	// (similar to echo.StaticFS but with gzip middleware enabled)
// 	e.GET(
// 		trailedPath+"build/*",
// 		echo.StaticDirectoryHandler(ui.BuildDirFS, false),
// 		middleware.Gzip(),
// 	)
// 	e.GET(
// 		trailedPath+"*",
// 		echo.StaticDirectoryHandler(ui.BuildIndexFS, false),
// 		middleware.Gzip(),
// 	)

// 	return nil
// }
